routes/web.php
<?php

use App\Http\Controllers\CategoryController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\ProductModelController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\TransactionController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', [CustomerController::class, 'index'])->name('home');

Route::group(['middleware' => ['auth']], function () {
    Route::get('/products/{id}', [CustomerController::class, 'showProduct'])->name('product.show');
    Route::post('/products/{id}/addToCart', [CustomerController::class, 'addToCart'])->name('cart.add');
    Route::get('/cart', [CustomerController::class, 'cart'])->name('cart');
    Route::get('/cart/{id}/remove', [CustomerController::class, 'removeFromCart'])->name('cart.remove');

    // Transactions
    Route::prefix('transactions')->name('transactions.')->group(function() {
        Route::get('/', [TransactionController::class, 'index'])->name('index');
        Route::get('/transactions/{id}', [TransactionController::class, 'show'])->name('show');
        Route::get('/checkout/overview', [TransactionController::class, 'overview'])->name('overview');
        Route::post('/checkout', [TransactionController::class, 'checkout'])->name('checkout');
    });
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware('auth')->name('dashboard');

Route::prefix('admin')->middleware('auth.admin')->group(function() {

    Route::name('admin.')->group(function() {
        Route::get('/dashboard', [AdminController::class, 'index'])->name('dashboard');

        Route::resource('category', CategoryController::class);
        Route::resource('user', UserController::class);
        Route::resource('product', ProductController::class);
        Route::resource('product.model', ProductModelController::class);
    });
});

require __DIR__.'/auth.php';

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;
}

app/Models/CustomerAddress.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class CustomerAddress extends Model
{
    use HasFactory;

    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;

    public function productModels()
    {
        return $this->hasMany(ProductModel::class);
    }
}

app/Models/ProductCategory.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class ProductCategory extends Model
{
    use HasFactory;
}

app/Models/ProductModel.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class ProductModel extends Model
{
    use HasFactory;

    public function product()
    {
        return $this->belongsTo(Product::class);
    }
}

app/Models/Transaction.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Transaction extends Model
{
    use HasFactory;
}

app/Models/TransactionItem.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class TransactionItem extends Model
{
    use HasFactory;
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'phone',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function customerAddresses()
    {
        return $this->hasMany(CustomerAddress::class);
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = DB::select('
            select p.id, max(p.name) as name, max(p.brand) as brand, count(m.id) as models
            from products p
            left join product_models m on p.id = m.product_id
            group by p.id
        ');

        return view('admin.product.index', ['products' => $products]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = DB::select('select * from categories');
        return view('admin.product.create', ['categories' => $categories]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|string',
            'brand' => 'required|string'
        ]);
        DB::transaction(function () use ($request) {
            DB::insert('insert into products(name, brand) values(?, ?)', [$request->input('name'), $request->input('brand')]);
            $id = DB::select('select last_insert_id() as id')[0]->id;
            $categories = [];
            foreach ($request->input('categories', []) as $value) {
                $categories[$value] = null;
            }
            foreach ($categories as $key => $value) {
                DB::insert('insert into product_categories(product_id, category_id) values(?, ?)', [$id, $key]);
            }
        });
        return redirect(route('admin.product.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $product = DB::select('select * from products where id = ?', [$id])[0];
        return view('admin.product.show', ['product'=>$product]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $categories = DB::select('select * from categories');
        $product = DB::select('select * from products where id = ?', [$id])[0];
        $productCategories = DB::select('select * from product_categories where product_id = ?', [$id]);
        return view('admin.product.edit', ['product'=>$product, 'productCategories' => $productCategories, 'categories' => $categories]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name' => 'required|string',
            'brand' => 'required|string',
        ]);
        DB::transaction(function () use ($request, $id) {
            DB::update('update products set name = ?, brand = ? where id = ?', [$request->input('name'), $request->input('brand'), $id]);

            // Reset categories
            DB::delete('delete from product_categories where product_id = ?', [$id]);

            // Update categories
            $categories = [];
            foreach ($request->input('categories', []) as $value) {
                $categories[$value] = null;
            }
            foreach ($categories as $key => $value) {
                DB::insert('insert into product_categories(product_id, category_id) values(?, ?)', [$id, $key]);
            }
        });

        return redirect(route('admin.product.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        DB::delete('delete from products where id = ?', [$id]);
        return redirect(route('admin.product.index'));
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/admin/product/model/create.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="text-xl font-semibold leading-tight text-gray-800">
            Creating new <a href="{{ route('admin.product.model.index', $product->id) }}">{{ $product->name }}</a>'s model
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="mx-auto max-w-7xl sm:px-6 lg:px-8">
            <div class="overflow-hidden bg-white shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">

                    <!-- Validation Errors -->
                    <x-auth-validation-errors class="mb-4" :errors="$errors" />

                    <form method="POST" action="{{ route('admin.product.model.store', $product->id) }}">
                        @csrf

                        <!-- Size -->
                        <div>
                            <x-label for="size" :value="__('Size')" />

                            <x-input id="size" class="block w-full mt-1" type="text" name="size" :value="old('size')" required autofocus />
                        </div>

                        <!-- Color -->
                        <div>
                            <x-label for="color" :value="__('Color')" />

                            <x-input id="color" class="block w-full mt-1" type="text" name="color" :value="old('color')" required autofocus />
                        </div>

                        <!-- Price -->
                        <div>
                            <x-label for="price" :value="__('Price')" />

                            <x-input id="price" class="block w-full mt-1" type="number" name="price" :value="old('price')" required autofocus />
                        </div>

                        <div class="flex items-center justify-end mt-4">
                            <x-button class="ml-3">
                                {{ __('Create') }}
                            </x-button>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>

</x-app-layout>

resources/views/admin/product/model/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="text-xl font-semibold leading-tight text-gray-800">
            Editing <a href="{{ route('admin.product.model.index', $product->id) }}">{{ $product->name }}</a>'s model
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="mx-auto max-w-7xl sm:px-6 lg:px-8">
            <div class="overflow-hidden bg-white shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">

                    <!-- Validation Errors -->
                    <x-auth-validation-errors class="mb-4" :errors="$errors" />

                    <form method="POST" action="{{ route('admin.product.model.update', [$product->id, $model->id]) }}">
                        @csrf
                        @method('PUT')

                        <!-- Size -->
                        <div>
                            <x-label for="size" :value="__('Size')" />

                            <x-input id="size" class="block w-full mt-1" type="text" name="size" :value="old('size') ? old ('size') : $model->size" required autofocus />
                        </div>

                        <!-- Color -->
                        <div>
                            <x-label for="color" :value="__('Color')" />

                            <x-input id="color" class="block w-full mt-1" type="text" name="color" :value="old('color') ? old ('color') : $model->color" required autofocus />
                        </div>

                        <!-- Price -->
                        <div>
                            <x-label for="price" :value="__('Price')" />

                            <x-input id="price" class="block w-full mt-1" type="number" name="price" :value="old('price') ? old ('price') : $model->price" required autofocus />
                        </div>

                        <div class="flex justify-end">
                            <div class="flex items-center justify-end mt-4">
                                <x-button class="ml-3">
                                    {{ __('Save') }}
                                </x-button>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/admin/product/model/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="text-xl font-semibold leading-tight text-gray-800">
            {{ __('Models of '.$product->name) }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="mx-auto max-w-7xl sm:px-6 lg:px-8">
            <div class="overflow-hidden bg-white shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">

                    <table class="table w-full mb-5 table-auto">
                        <thead>
                            <tr>
                                <th>Size</th>
                                <th>Color</th>
                                <th>Price</th>
                                <th class="w-44">Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($models as $model)
                                <tr class="transition-colors hover:bg-gray-200">
                                    <td class="p-2 border-b-2">
                                        <a href="{{ route('admin.product.model.show', [$product->id, $model->id]) }}">{{ $model->size }}</a>
                                    </td>
                                    <td class="p-2 border-b-2">{{ $model->color }}</td>
                                    <td class="p-2 border-b-2">{{ $model->price }}</td>
                                    <td class="flex p-2">
                                        <x-button-link href="{{ route('admin.product.model.edit', [$product->id, $model->id]) }}">
                                            Edit
                                        </x-button-link>
                                        <form class="mx-2" action="{{ route('admin.product.model.destroy', [$product->id, $model->id]) }}" method="post">
                                            @csrf
                                            @method('DELETE')
                                            <x-button class="bg-red-800 hover:bg-red-500">
                                                Delete
                                            </x-button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>

                    <div class="flex justify-end">
                        <x-button-link href="{{ route('admin.product.model.create', $product->id) }}">
                            Create
                        </x-button-link>
                    </div>

                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/admin/product/model/show.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="text-xl font-semibold leading-tight text-gray-800">
            Showing <a href="{{ route('admin.product.model.index', $product->id) }}">{{ $product->name }}</a>'s model
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="mx-auto max-w-7xl sm:px-6 lg:px-8">
            <div class="overflow-hidden bg-white shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">

                    <!-- Size -->
                    <div>
                        <x-label for="size" :value="__('Size')" />

                        <x-input id="size" class="block w-full mt-1" type="text" name="size" :value="old('size') ? old ('size') : $model->size" readonly autofocus />
                    </div>

                    <!-- Color -->
                    <div>
                        <x-label for="color" :value="__('Color')" />

                        <x-input id="color" class="block w-full mt-1" type="text" name="color" :value="old('color') ? old ('color') : $model->color" readonly autofocus />
                    </div>

                    <!-- Price -->
                    <div>
                        <x-label for="price" :value="__('Price')" />

                        <x-input id="price" class="block w-full mt-1" type="number" name="price" :value="old('price') ? old ('price') : $model->price" readonly autofocus />
                    </div>

                    <div class="flex justify-end mt-2">
                        <x-button-link href="{{ route('admin.product.model.edit', [$product->id, $model->id]) }}">
                            {{ __('Edit')}}
                        </x-button-link>
                    </div>

                </div>
            </div>
        </div>
    </div>
</x-app-layout>