routes/web.php
<?php

use App\Http\Controllers\CategoryController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\ProductModelController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\TransactionController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', [CustomerController::class, 'index'])->name('home');

Route::group(['middleware' => ['auth']], function () {
    Route::get('/products/{id}', [CustomerController::class, 'showProduct'])->name('product.show');
    Route::post('/products/{id}/addToCart', [CustomerController::class, 'addToCart'])->name('cart.add');
    Route::get('/cart', [CustomerController::class, 'cart'])->name('cart');
    Route::get('/cart/{id}/remove', [CustomerController::class, 'removeFromCart'])->name('cart.remove');

    // Transactions
    Route::prefix('transactions')->name('transactions.')->group(function() {
        Route::get('/', [TransactionController::class, 'index'])->name('index');
        Route::get('/transactions/{id}', [TransactionController::class, 'show'])->name('show');
        Route::get('/checkout/overview', [TransactionController::class, 'overview'])->name('overview');
        Route::post('/checkout', [TransactionController::class, 'checkout'])->name('checkout');
    });
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware('auth')->name('dashboard');

Route::prefix('admin')->middleware('auth.admin')->group(function() {

    Route::name('admin.')->group(function() {
        Route::get('/dashboard', [AdminController::class, 'index'])->name('dashboard');

        Route::resource('category', CategoryController::class);
        Route::resource('user', UserController::class);
        Route::resource('product', ProductController::class);
        Route::resource('product.model', ProductModelController::class);
    });
});

require __DIR__.'/auth.php';

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;

    public function productModels()
    {
        return $this->hasMany(ProductModel::class);
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = DB::select('
            select p.id, max(p.name) as name, max(p.brand) as brand, count(m.id) as models
            from products p
            left join product_models m on p.id = m.product_id
            group by p.id
        ');

        return view('admin.product.index', ['products' => $products]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = DB::select('select * from categories');
        return view('admin.product.create', ['categories' => $categories]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|string',
            'brand' => 'required|string'
        ]);
        DB::transaction(function () use ($request) {
            DB::insert('insert into products(name, brand) values(?, ?)', [$request->input('name'), $request->input('brand')]);
            $id = DB::select('select last_insert_id() as id')[0]->id;
            $categories = [];
            foreach ($request->input('categories', []) as $value) {
                $categories[$value] = null;
            }
            foreach ($categories as $key => $value) {
                DB::insert('insert into product_categories(product_id, category_id) values(?, ?)', [$id, $key]);
            }
        });
        return redirect(route('admin.product.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $product = DB::select('select * from products where id = ?', [$id])[0];
        return view('admin.product.show', ['product'=>$product]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $categories = DB::select('select * from categories');
        $product = DB::select('select * from products where id = ?', [$id])[0];
        $productCategories = DB::select('select * from product_categories where product_id = ?', [$id]);
        return view('admin.product.edit', ['product'=>$product, 'productCategories' => $productCategories, 'categories' => $categories]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name' => 'required|string',
            'brand' => 'required|string',
        ]);
        DB::transaction(function () use ($request, $id) {
            DB::update('update products set name = ?, brand = ? where id = ?', [$request->input('name'), $request->input('brand'), $id]);

            // Reset categories
            DB::delete('delete from product_categories where product_id = ?', [$id]);

            // Update categories
            $categories = [];
            foreach ($request->input('categories', []) as $value) {
                $categories[$value] = null;
            }
            foreach ($categories as $key => $value) {
                DB::insert('insert into product_categories(product_id, category_id) values(?, ?)', [$id, $key]);
            }
        });

        return redirect(route('admin.product.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        DB::delete('delete from products where id = ?', [$id]);
        return redirect(route('admin.product.index'));
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/admin/product/create.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="text-xl font-semibold leading-tight text-gray-800">
            {{ __('Create Product') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="mx-auto max-w-7xl sm:px-6 lg:px-8">
            <div class="overflow-hidden bg-white shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">

                    <!-- Validation Errors -->
                    <x-auth-validation-errors class="mb-4" :errors="$errors" />

                    <form method="POST" action="{{ route('admin.product.store') }}">
                        @csrf

                        <!-- Name -->
                        <div>
                            <x-label for="name" :value="__('Name')" />

                            <x-input id="name" class="block w-full mt-1" type="name" name="name" :value="old('name')" required autofocus />
                        </div>

                        <!-- Brand -->
                        <div>
                            <x-label for="brand" :value="__('Brand')" />

                            <x-input id="brand" class="block w-full mt-1" type="brand" name="brand" :value="old('brand')" required autofocus />
                        </div>

                        <!-- Categories -->
                        <div class="mt-4">
                            <x-label for="categories" :value="__('Categories')" />
                        </div>

                        <div x-data="categories" x-init="init($refs)">
                            <div x-ref="categories">
                                <div x-ref="categorySelectRef" class="flex flex-row hidden mt-2">
                                    <div class="w-10/12">
                                        <x-select id="selection" class="w-full">
                                            @foreach($categories as $category)
                                            <option value="{{ $category->id }}">{{ $category->name }}</option>
                                            @endforeach
                                        </x-select>
                                    </div>

                                    <div id="category-remove" class="flex justify-end w-2/12 my-auto">
                                        <x-button-link href="#!" id="remove-button">Remove</x-button-link>
                                    </div>
                                </div>
                            </div>

                            <div class="flex justify-end mt-4">
                                <x-button-link href="#!" x-on:click="add($refs)" id="category-add">Add</x-button-link>
                            </div>
                        </div>

                        <div class="flex items-center justify-end mt-4">
                            <x-button class="ml-3">
                                {{ __('Create') }}
                            </x-button>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
    @push('scripts')
    <script>
        var categories = {
            count: 1,
            ref: null,
            categorySelects : [],
            init(refs) {
                this.ref = refs;
                if (!refs.categorySelect) return;

                let categorySelect = refs.categorySelect;
                this.categorySelects.push(categorySelect);
                var removeButton = categorySelect.querySelector("#remove-button");
                removeButton.addEventListener("click", () => this.remove(categorySelect));
            },
            remove(category) {
                if (this.count-1 <= 0) return;
                let index = this.categorySelects.indexOf(category);
                delete this.categorySelects[index];
                category.remove();
                this.count--;
            },
            add(refs) {
                let index = (function() {
                    return categories.count.toString();
                })();
                this.count++;
                let newCategory = refs.categorySelectRef.cloneNode(true);
                newCategory.classList.remove("hidden");
                newCategory.querySelector("#selection").setAttribute("name", "categories[]");
                this.categorySelects.push(newCategory);
                var removeButton = newCategory.querySelector("#remove-button");
                removeButton.addEventListener("click", () => this.remove(newCategory));
                refs.categories.appendChild(newCategory);
            }
        }
    </script>
    @endpush

</x-app-layout>

resources/views/admin/product/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="text-xl font-semibold leading-tight text-gray-800">
            {{ __('Editing product \''.$product->name.'\'') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="mx-auto max-w-7xl sm:px-6 lg:px-8">
            <div class="overflow-hidden bg-white shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">

                    <!-- Validation Errors -->
                    <x-auth-validation-errors class="mb-4" :errors="$errors" />

                    <form method="POST" action="{{ route('admin.product.update', $product->id) }}">
                        @csrf
                        @method('PUT')

                        <!-- Name -->
                        <div>
                            <x-label for="name" :value="__('Name')" />

                            <x-input id="name" class="block w-full mt-1" type="name" name="name" :value="old('name') ? old('name') : $product->name" required autofocus />
                        </div>

                        <!-- Brand -->
                        <div>
                            <x-label for="brand" :value="__('Brand')" />

                            <x-input id="brand" class="block w-full mt-1" type="brand" name="brand" :value="old('brand') ? old('brand') : $product->brand" required autofocus />
                        </div>

                        <!-- Categories -->
                        <div class="mt-4">
                            <x-label for="categories" :value="__('Categories')" />
                        </div>

                        <div x-data="categories" x-init="init($refs)">
                            <div x-ref="categories">
                                <div x-ref="categorySelectRef" class="flex flex-row hidden mt-2">
                                    <div class="w-10/12">
                                        <x-select id="selection" class="w-full">
                                            @foreach($categories as $category)
                                            <option value="{{ $category->id }}">{{ $category->name }}</option>
                                            @endforeach
                                        </x-select>
                                    </div>

                                    <div id="category-remove" class="flex justify-end w-2/12 my-auto">
                                        <x-button-link href="#!" id="remove-button">Remove</x-button-link>
                                    </div>
                                </div>

                                @foreach($productCategories as $key => $value)
                                <div id="category-select" x-ref="categorySelect" class="flex flex-row mt-2">
                                    <div class="w-10/12">
                                        <x-select class="w-full" name="categories[]">
                                            @foreach($categories as $category)
                                                @if ($value->category_id == $category->id)
                                                    <option value="{{ $category->id }}" selected>{{ $category->name }}</option>
                                                @else
                                                    <option value="{{ $category->id }}">{{ $category->name }}</option>
                                                @endif
                                            @endforeach
                                        </x-select>
                                    </div>

                                    <div id="category-remove" class="flex justify-end w-2/12 my-auto">
                                        <x-button-link href="#!" id="remove-button">Remove</x-button-link>
                                    </div>
                                </div>
                                @endforeach
                            </div>

                            <div class="flex justify-end mt-4">
                                <x-button-link href="#!" x-on:click="add($refs)" id="category-add">Add</x-button-link>
                            </div>
                        </div>

                        <div class="flex justify-end">
                            <div class="flex items-center justify-end mt-4">
                                <x-button class="ml-3">
                                    {{ __('Save') }}
                                </x-button>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
    @push('scripts')
    <script>
        var categories = {
            count: 1,
            ref: null,
            categorySelects : [],
            init(refs) {
                this.ref = refs;
                categorySelects = refs.categories.querySelectorAll("#category-select");
                if (!refs.categorySelect) return;

                for (var i = 0; i < categorySelects.length; i++)
                {
                    let categorySelect = categorySelects[i];
                    this.categorySelects.push(categorySelect);
                    var removeButton = categorySelect.querySelector("#remove-button");
                    removeButton.addEventListener("click", () => this.remove(categorySelect));
                }
                this.count = categorySelects.length;
            },
            remove(category) {
                if (this.count-1 <= 0) return;
                console.log(category);
                let index = this.categorySelects.indexOf(category);
                delete this.categorySelects[index];
                category.remove();
                this.count--;
            },
            add(refs) {
                let index = (function() {
                    return categories.count.toString();
                })();
                this.count++;
                let newCategory = refs.categorySelectRef.cloneNode(true);
                newCategory.classList.remove("hidden");
                newCategory.querySelector("#selection").setAttribute("name", "categories[]");
                this.categorySelects.push(newCategory);
                var removeButton = newCategory.querySelector("#remove-button");
                removeButton.addEventListener("click", () => this.remove(newCategory));
                refs.categories.appendChild(newCategory);
            }
        }
    </script>
    @endpush
</x-app-layout>

resources/views/admin/product/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="text-xl font-semibold leading-tight text-gray-800">
            {{ __('Product') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="mx-auto max-w-7xl sm:px-6 lg:px-8">
            <div class="overflow-hidden bg-white shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">

                    <table class="table w-full mb-5 table-auto">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Brand</th>
                                <th>Models</th>
                                <th class="w-44">Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($products as $product)
                                <tr class="transition-colors hover:bg-gray-200">
                                    <td class="p-2 border-b-2">
                                        <a href="{{ route('admin.product.show', $product->id) }}">{{ $product->name }}</a>
                                    </td>
                                    <td class="p-2 border-b-2">{{ $product->brand }}</td>
                                    <td class="p-2 border-b-2">{{ $product->models }}</td>
                                    <td class="flex p-2">
                                        <x-button-link class="ml-2" href="{{ route('admin.product.model.index', $product->id) }}">
                                            Models
                                        </x-button-link>
                                        <x-button-link class="ml-2" href="{{ route('admin.product.edit', $product->id) }}">
                                            Edit
                                        </x-button-link>
                                        <form class="ml-2" action="{{ route('admin.product.destroy', $product->id) }}" method="post">
                                            @csrf
                                            @method('DELETE')
                                            <x-button class="bg-red-800 hover:bg-red-500">
                                                Delete
                                            </x-button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>

                    <div class="flex justify-end">
                        <x-button-link href="{{ route('admin.product.create') }}">
                            Create
                        </x-button-link>
                    </div>

                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/admin/product/show.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Showing product \''.$product->name.'\'') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">

                    <!-- Name -->
                    <div>
                        <x-label for="name" :value="__('Name')" />

                        <x-input id="name" class="block mt-1 w-full" type="name" name="name" :value="old('name') ? old('name') : $product->name" required autofocus />
                    </div>

                    <!-- Brand -->
                    <div>
                        <x-label for="brand" :value="__('Brand')" />

                        <x-input id="brand" class="block mt-1 w-full" type="brand" name="brand" :value="$product->brand" readonly autofocus />
                    </div>

                    <div class="flex items-center justify-end mt-4">
                        <x-button-link href="{{ route('admin.product.edit', $product->id) }}" class="ml-3">
                            {{ __('Edit') }}
                        </x-button-link>
                    </div>

                </div>
            </div>
        </div>
    </div>
</x-app-layout>