routes/web.php
<?php

use App\Http\Controllers\CategoryController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\ProductModelController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\TransactionController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', [CustomerController::class, 'index'])->name('home');

Route::group(['middleware' => ['auth']], function () {
    Route::get('/products/{id}', [CustomerController::class, 'showProduct'])->name('product.show');
    Route::post('/products/{id}/addToCart', [CustomerController::class, 'addToCart'])->name('cart.add');
    Route::get('/cart', [CustomerController::class, 'cart'])->name('cart');
    Route::get('/cart/{id}/remove', [CustomerController::class, 'removeFromCart'])->name('cart.remove');

    // Transactions
    Route::prefix('transactions')->name('transactions.')->group(function() {
        Route::get('/', [TransactionController::class, 'index'])->name('index');
        Route::get('/transactions/{id}', [TransactionController::class, 'show'])->name('show');
        Route::get('/checkout/overview', [TransactionController::class, 'overview'])->name('overview');
        Route::post('/checkout', [TransactionController::class, 'checkout'])->name('checkout');
    });
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware('auth')->name('dashboard');

Route::prefix('admin')->middleware('auth.admin')->group(function() {

    Route::name('admin.')->group(function() {
        Route::get('/dashboard', [AdminController::class, 'index'])->name('dashboard');

        Route::resource('category', CategoryController::class);
        Route::resource('user', UserController::class);
        Route::resource('product', ProductController::class);
        Route::resource('product.model', ProductModelController::class);
    });
});

require __DIR__.'/auth.php';

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'phone',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function customerAddresses()
    {
        return $this->hasMany(CustomerAddress::class);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Validation\Rule;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    const ROUTE_INDEX = 'admin.user.index';

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = DB::select('select * from users');
        return view(UserController::ROUTE_INDEX, ['users'=>$users]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.user.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|string|max:255',
            'email' => 'required|string|email|max:255|unique:users',
            'password' => 'required|string|confirmed|min:8',
            'phone' => 'required|string|numeric|min:10',
            'role' => ['required', 'string', Rule::in(['Admin', 'Customer'])],
        ]);
        DB::transaction(function () use ($request) {
            DB::insert('insert into users(name, email, password, phone, role) values(:name, :email, :password, :phone, :role)', [
                'name' => $request->input('name'),
                'email' => $request->input('email'),
                'password' => Hash::make($request->input('password')),
                'phone' => $request->input('phone'),
                'role' => $request->input('role')
            ]);
            $id = DB::select('select last_insert_id() as id from users')[0]->id;

            $customerAddresses = [];
            foreach ($request->input('addresses', []) as $key => $value) {
                $phones = $request->input('phones', []);
                $customerAddresses[]['address'] = $value;
                $customerAddresses[$key]['phone'] = $phones[$key];
            }

            foreach ($customerAddresses as $value) {
                DB::insert('insert into customer_addresses(user_id, address, phone) values(?, ?, ?)', [$id, $value['address'], $value['phone']]);
            }
        });
        return redirect(route(UserController::ROUTE_INDEX));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = DB::select('select * from users where id = ?', [$id])[0];
        return view('admin.user.show', ['user'=>$user]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = DB::select('select * from users where id = ?', [$id])[0];
        $customerAddresses = DB::select('select * from customer_addresses where user_id = ?', [$id]);
        return view('admin.user.edit', ['user' => $user, 'customerAddresses' => $customerAddresses]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name' => 'required|string|max:255',
            'email' => ['required', 'string', 'email', 'max:255', Rule::unique('users')->ignore($id)],
            'phone' => 'required|string|numeric|min:10',
            'role' => ['required', 'string', Rule::in(['Admin', 'Customer'])],
        ]);
        DB::transaction(function () use ($request, $id) {
            DB::update('update users set name = :name, email = :email, phone = :phone, role = :role where id = :id', [
                'name' => $request->input('name'),
                'email' => $request->input('email'),
                'phone' => $request->input('phone'),
                'role' => $request->input('role'),
                'id' => $id
            ]);

            DB::delete('delete from customer_addresses where user_id = ?', [$id]);

            $customerAddresses = [];
            foreach ($request->input('addresses', []) as $key => $value) {
                $phones = $request->input('phones', []);
                $customerAddresses[$key]['address'] = $value;
                $customerAddresses[$key]['phone'] = $phones[$key];
            }

            foreach ($customerAddresses as $value) {
                DB::insert('insert into customer_addresses(user_id, address, phone) values(?, ?, ?)', [$id, $value['address'], $value['phone']]);
            }
        });
        return redirect(route(UserController::ROUTE_INDEX));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        DB::delete('delete from users where id = ?', [$id]);
        return redirect(route(UserController::ROUTE_INDEX));
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/admin/user/create.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="text-xl font-semibold leading-tight text-gray-800">
            {{ __('Create user') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="mx-auto max-w-7xl sm:px-6 lg:px-8">
            <div class="overflow-hidden bg-white shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">

                    <!-- Validation Errors -->
                    <x-auth-validation-errors class="mb-4" :errors="$errors" />

                    <form method="POST" action="{{ route('admin.user.store') }}">
                        @csrf

                        <!-- Name -->
                        <div>
                            <x-label for="name" :value="__('Name')" />

                            <x-input id="name" class="block w-full mt-1" type="text" name="name" :value="old('name')" required autofocus />
                        </div>

                        <!-- Phone -->
                        <div class="mt-4">
                            <x-label for="phone" :value="__('Phone')" />

                            <x-input id="phone" class="block w-full mt-1" type="text" name="phone" :value="old('phone')" required />
                        </div>

                        <!-- Email Address -->
                        <div class="mt-4">
                            <x-label for="email" :value="__('Email')" />

                            <x-input id="email" class="block w-full mt-1" type="email" name="email" :value="old('email')" required />
                        </div>

                        <!-- Role -->
                        <div class="mt-4">
                            <x-label for="role" :value="__('Role')" />
                            <x-select class="w-full" name="role" :value="old('role')">
                                <option value="Customer">Customer</option>
                                <option value="Admin">Admin</option>
                            </x-select>
                        </div>

                        <!-- Password -->
                        <div class="mt-4">
                            <x-label for="password" :value="__('Password')" />

                            <x-input id="password" class="block w-full mt-1"
                                            type="password"
                                            name="password"
                                            required autocomplete="new-password" />
                        </div>

                        <!-- Confirm Password -->
                        <div class="mt-4">
                            <x-label for="password_confirmation" :value="__('Confirm Password')" />

                            <x-input id="password_confirmation" class="block w-full mt-1"
                                            type="password"
                                            name="password_confirmation" required />
                        </div>

                        <!-- Addresses -->
                        <div x-data="addresses" class="mt-4">
                            <div x-ref="addresses">
                                <x-label for="addresses" :value="__('Addresses')"/>
                                <div x-ref="addressInputRef" class="hidden">
                                    <x-input type="text" placeholder="Full Address" class="w-11/12 mt-3 mr-3" id="address-input" />
                                    <x-input type="text" placeholder="Phone" class="w-3/12 mt-3 mr-3" id="address-phone" />
                                    <x-button-link href="#!" class="w-1/12 mt-3" id="remove-button" >{{ __('Remove') }}</x-button-link>
                                </div>
                            </div>
                            <div class="flex justify-end mt-4">
                                <x-button-link href="#!" x-on:click="add($refs)">{{ __('Add New Address') }}</x-button-link>
                            </div>
                        </div>

                        <div class="flex items-center justify-end mt-4">
                            <x-button class="ml-3">
                                {{ __('Create') }}
                            </x-button>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
    @push('scripts')
        <script>
            var addresses = {
                count: 0,
                ref: null,
                addressInputs: [],
                remove(addressInput) {
                    let index = this.addressInputs.indexOf(addressInput);
                    delete this.addressInputs[index];
                    addressInput.remove();
                    this.count--;
                },
                add(refs) {
                    this.count++;
                    let newAddress = refs.addressInputRef.cloneNode(true);
                    newAddress.classList.remove("hidden");
                    newAddress.classList.add("flex");
                    newAddress.querySelector("#address-input").setAttribute("name", "addresses[]");
                    newAddress.querySelector("#address-phone").setAttribute("name", "phones[]");
                    this.addressInputs.push(newAddress);
                    var removeButton = newAddress.querySelector("#remove-button");
                    removeButton.addEventListener("click", () => this.remove(newAddress));
                    refs.addresses.appendChild(newAddress);
                }
            }
        </script>
    @endpush
</x-app-layout>

resources/views/admin/user/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="text-xl font-semibold leading-tight text-gray-800">
            {{ __('Editing user \''.$user->name.'\'') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="mx-auto max-w-7xl sm:px-6 lg:px-8">
            <div class="overflow-hidden bg-white shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">

                    <!-- Validation Errors -->
                    <x-auth-validation-errors class="mb-4" :errors="$errors" />

                    <form method="POST" action="{{ route('admin.user.update', $user->id) }}">
                        @csrf
                        @method('PUT')

                        <!-- Name -->
                        <div>
                            <x-label for="name" :value="__('Name')" />

                            <x-input id="name" class="block w-full mt-1" type="text" name="name" :value="old('name') ? old('name') : $user->name" required autofocus />
                        </div>

                        <!-- Phone -->
                        <div class="mt-4">
                            <x-label for="phone" :value="__('Phone')" />

                            <x-input id="phone" class="block w-full mt-1" type="text" name="phone" :value="old('phone') ? old('phone') : $user->phone" required />
                        </div>

                        <!-- Email Address -->
                        <div class="mt-4">
                            <x-label for="email" :value="__('Email')" />

                            <x-input id="email" class="block w-full mt-1" type="email" name="email" :value="old('email') ? old('email') : $user->email" required />
                        </div>

                        <!-- Role -->
                        <div class="mt-4">
                            <x-label for="role" :value="__('Role')" />
                            <x-select class="w-full" name="role">
                                <option value="Customer" {{ $user->role=='Customer' ? __('selected') : '' }}>Customer</option>
                                <option value="Admin" {{ $user->role=='Admin' ? __('selected') : '' }}>Admin</option>
                            </x-select>
                        </div>

                        <!-- Addresses -->
                        <div x-data="addresses" x-init="init($refs)" class="mt-4">
                            <div x-ref="addresses">
                                <x-label for="addresses" :value="__('Addresses')"/>
                                <div x-ref="addressInputRef" class="hidden">
                                    <x-input type="text" placeholder="Full Address" class="w-11/12 mt-3 mr-3" id="address-input" />
                                    <x-input type="text" placeholder="Phone" class="w-3/12 mt-3 mr-3" id="address-phone" />
                                    <x-button-link href="#!" class="w-1/12 mt-3" id="remove-button" >{{ __('Remove') }}</x-button-link>
                                </div>
                                @foreach($customerAddresses as $customerAddress)
                                <div id="address-item" class="flex">
                                    <x-input id="address-input" type="text" placeholder="Full Address" class="w-11/12 mt-3 mr-3" name="addresses[]" :value="$customerAddress->address" />
                                    <x-input id="address-phone" type="text" placeholder="Phone" class="w-3/12 mt-3 mr-3" name="phones[]" :value="$customerAddress->phone" />
                                    <x-button-link href="#!" class="w-1/12 mt-3" id="remove-button" >{{ __('Remove') }}</x-button-link>
                                </div>
                                @endforeach
                            </div>
                            <div class="flex justify-end mt-4">
                                <x-button-link href="#!" x-on:click="add($refs)">{{ __('Add New Address') }}</x-button-link>
                            </div>
                        </div>

                        <div class="flex justify-end">
                            <div class="flex items-center justify-end mt-4">
                                <x-button class="ml-3">
                                    {{ __('Save') }}
                                </x-button>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
    @push('scripts')
        <script>
            var addresses = {
                count: 0,
                ref: null,
                addressInputs: [],
                init(refs) {
                    this.ref = refs;
                    if (!refs.addressInputRef) return;

                    let addressItems = refs.addresses.querySelectorAll("#address-item");
                    for (var i = 0; i < addressItems.length; i++) {
                        let addressItem = addressItems[i];
                        this.addressInputs.push(addressItem);
                        var removeButton = addressItem.querySelector("#remove-button");
                        removeButton.addEventListener("click", () => this.remove(addressItem));
                        this.count++;
                    }
                },
                remove(addressInput) {
                    let index = this.addressInputs.indexOf(addressInput);
                    delete this.addressInputs[index];
                    addressInput.remove();
                    this.count--;
                },
                add(refs) {
                    this.count++;
                    let newAddress = refs.addressInputRef.cloneNode(true);
                    newAddress.classList.remove("hidden");
                    newAddress.classList.add("flex");
                    newAddress.querySelector("#address-input").setAttribute("name", "addresses[]");
                    newAddress.querySelector("#address-phone").setAttribute("name", "phones[]");
                    this.addressInputs.push(newAddress);
                    var removeButton = newAddress.querySelector("#remove-button");
                    removeButton.addEventListener("click", () => this.remove(newAddress));
                    refs.addresses.appendChild(newAddress);
                }
            }
        </script>
    @endpush
</x-app-layout>

resources/views/admin/user/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Users') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">

                    <table class="w-full mb-5 table table-auto">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Email</th>
                                <th>Phone</th>
                                <th>Role</th>
                                <th class="w-44">Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($users as $user)
                                <tr class="hover:bg-gray-200 transition-colors">
                                    <td class="border-b-2 p-2">
                                        <a href="{{ route('admin.user.show', $user->id) }}">{{ $user->name }}</a>
                                    </td>
                                    <td class="border-b-2 p-2">
                                        {{ $user->email }}
                                    </td>
                                    <td class="border-b-2 p-2">
                                        {{ $user->phone }}
                                    </td>
                                    <td class="border-b-2 p-2">
                                        {{ $user->role }}
                                    </td>
                                    <td class="p-2 flex">
                                        <x-button-link href="{{ route('admin.user.edit', $user->id) }}">
                                            Edit
                                        </x-button-link>
                                        <form class="mx-2" action="{{ route('admin.user.destroy', $user->id) }}" method="post">
                                            @csrf
                                            @method('DELETE')
                                            <x-button class="bg-red-800 hover:bg-red-500">
                                                Delete
                                            </x-button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>

                    <div class="flex justify-end">
                        <x-button-link href="{{ route('admin.user.create') }}">
                            Create
                        </x-button-link>
                    </div>

                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/admin/user/show.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Showing user \''.$user->name.'\'') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">


                    <!-- Name -->
                    <div>
                        <x-label for="name" :value="__('Name')" />

                        <x-input id="name" class="block mt-1 w-full" type="text" name="name" :value="old('name') ? old('name') : $user->name" readonly autofocus />
                    </div>

                    <!-- Phone -->
                    <div class="mt-4">
                        <x-label for="phone" :value="__('Phone')" />

                        <x-input id="phone" class="block mt-1 w-full" type="text" name="phone" :value="old('phone') ? old('phone') : $user->phone" readonly />
                    </div>

                    <!-- Email Address -->
                    <div class="mt-4">
                        <x-label for="email" :value="__('Email')" />

                        <x-input id="email" class="block mt-1 w-full" type="email" name="email" :value="old('email') ? old('email') : $user->email" readonly />
                    </div>

                    <div class="flex items-center justify-end mt-4">
                        <x-button-link href="{{ route('admin.user.edit', $user->id) }}" class="ml-3">
                            {{ __('Edit') }}
                        </x-button-link>
                    </div>

                </div>
            </div>
        </div>
    </div>
</x-app-layout>